# -*- coding: utf-8 -*-
"""Another copy of Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhpGZ1UdTkSOFH8KCwCbxUEqaEfmfPmG
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error

# Load and Process Data
df = pd.read_csv("/content/drive/MyDrive/Capstone/4G_daily_KPI_Summary_Site_Hourly_March_2-5_new.csv")

# Display Header
df.head()

# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'])

# Create new datetime column
df['datetime'] = df['date'] + pd.to_timedelta(df['hour'], unit='h')

# View result
print(df[['date', 'hour', 'datetime']].head())

import matplotlib.pyplot as plt

# Select one sample site
sample_site = df['site_name'].iloc[5]

# Filter data for that site
site_data = df[df['site_name'] == sample_site].sort_values('datetime')

# Plot traffic vs time
plt.figure(figsize=(14,6))

plt.plot(
    site_data['datetime'],
    site_data['sum_dl_traffic_volume_gb'],
    marker='o'
)

plt.title(f"Traffic Pattern for Site: {sample_site}")

plt.xlabel("Time")
plt.ylabel("DL Traffic Volume (GB)")

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Format Date Time
df['date'] = pd.to_datetime(df['date'])

df['datetime'] = (
    df['date'] +
    pd.to_timedelta(df['hour'], unit='h')
)

# Sort values
df = df.sort_values([
    'site_name',
    'datetime'
])

# Feature Engineering
def create_features(data):

    data = data.copy()

    # Time Features
    data['hour'] = data['datetime'].dt.hour
    data['dayofweek'] = data['datetime'].dt.dayofweek

    # Lag Features
    data['lag1'] = (
        data.groupby('site_name')
        ['sum_dl_traffic_volume_gb']
        .shift(1)
    )

    data['lag24'] = (
        data.groupby('site_name')
        ['sum_dl_traffic_volume_gb']
        .shift(24)
    )

    # Rolling Mean
    data['rolling_3'] = (
        data.groupby('site_name')
        ['sum_dl_traffic_volume_gb']
        .rolling(3)
        .mean()
        .reset_index(level=0, drop=True)
    )

    return data

# Apply feature engineering
df = create_features(df)

# Train and Validation Data Split
# TRAIN: 2nd -> 4th March
train_df = df[
    (df['date'] >= '2026-03-02') &
    (df['date'] <= '2026-03-04')
].copy()

# VALIDATION: 5th March
val_df = df[
    (df['date'] == '2026-03-05')
].copy()

# Remove NA generated from lagging
train_df = train_df.dropna()
val_df = val_df.dropna()


# Features and Traget Parameter
features = [
    'hour',
    'dayofweek',
    'sum_avg_connected_users',
    'sum_avg_dl_user_thp_qci_8_kbps_num',
    'sum_avg_dl_user_thp_qci_8_kbps_deno',
    'sum_avg_dl_user_thp_qci_9_kbps_num',
    'sum_avg_dl_user_thp_qci_9_kbps_deno',
    'lag1',
    'lag24',
    'rolling_3'
]

target = 'sum_dl_traffic_volume_gb'

# Train model per site
models = {}
results = []

site_list = train_df['site_name'].unique()

for site in site_list:

    # Train data
    site_train = train_df[
        train_df['site_name'] == site
    ]

    # Validation data
    site_val = val_df[
        val_df['site_name'] == site
    ]

    # Skip weak sites
    if len(site_train) < 24 or len(site_val) == 0:
        continue

    # Training the model
    X_train = site_train[features]
    y_train = site_train[target]

    model = XGBRegressor(
        n_estimators=100,
        max_depth=4,
        learning_rate=0.1,
        random_state=42
    )

    model.fit(X_train, y_train)

    models[site] = model

    # Validation
    X_val = site_val[features]
    y_val = site_val[target]

    y_pred = model.predict(X_val)

    # Generate Measuring Parameters
    mae = mean_absolute_error(y_val, y_pred)

    rmse = np.sqrt(
        mean_squared_error(y_val, y_pred)
    )

    r2 = r2_score(y_val, y_pred)

    results.append({
        'site_name': site,
        'MAE': mae,
        'RMSE': rmse,
        'R2': r2
    })

# Create Results Table
results_df = pd.DataFrame(results)

print(results_df)

# Print the Parameters
print("\n===== OVERALL PERFORMANCE =====")

print("Average MAE :", results_df['MAE'].mean())
print("Average RMSE:", results_df['RMSE'].mean())
print("Average R2  :", results_df['R2'].mean())

# Visualize Results
sample_site = results_df.iloc[0]['site_name']

site_val = val_df[
    val_df['site_name'] == sample_site
]

model = models[sample_site]

X_val = site_val[features]

site_val['prediction'] = model.predict(X_val)

# Plot a sample
plt.figure(figsize=(14,6))

plt.plot(
    site_val['datetime'],
    site_val[target],
    label='Actual'
)

plt.plot(
    site_val['datetime'],
    site_val['prediction'],
    label='Predicted'
)

plt.title(
    f"Traffic Forecast Validation - {sample_site}"
)

plt.xlabel("Datetime")

plt.ylabel("Traffic Volume (GB)")

plt.xticks(rotation=45)

plt.legend()

plt.tight_layout()

plt.show()

# Anomaly Detection using Trained ML Model
# Validation Data: 5th March
# Anomaly Threshold: 100%

ANOMALY_THRESHOLD = 1

anomaly_list = []

for site in models.keys():

    # Validation Data
    site_val = val_df[
        val_df['site_name'] == site
    ].copy()

    if len(site_val) == 0:
        continue

    model = models[site]

    # Actual Traffic Calculation
    site_val['ActualTraffic'] = (
        site_val['sum_dl_traffic_volume_gb']
    )

    # NULL Anomaly Detection
    site_val['is_null_anomaly'] = (
        site_val['ActualTraffic'].isnull()
    )

    # Predict non-NULL rows
    predict_df = site_val.dropna(subset=features)

    if len(predict_df) == 0:
        continue

    X_val = predict_df[features]

    # Prediction
    predict_df['PredictedTraffic'] = (
        model.predict(X_val)
    )

    # Avoid Divide by Zero
    predict_df = predict_df[
        predict_df['PredictedTraffic'] != 0
    ]

    # Deviation calculation
    predict_df['deviation'] = (
        abs(
            predict_df['ActualTraffic']
            -
            predict_df['PredictedTraffic']
        )
        /
        predict_df['PredictedTraffic']
    )

    # Deviation Anomaly iedntification
    predict_df['is_deviation_anomaly'] = (
        predict_df['deviation'] > ANOMALY_THRESHOLD
    )

    # FIinal Anomalies Data Set
    anomalies = predict_df[
        (
            predict_df['is_null_anomaly']
        )
        |
        (
            predict_df['is_deviation_anomaly']
        )
    ].copy()

    anomaly_list.append(anomalies)

# Combine All Anomalies
anomaly_df = pd.concat(anomaly_list)

# Select Output Columns
anomaly_df = anomaly_df[
    [
        'datetime',
        'site_name',
        'ActualTraffic',
        'PredictedTraffic',
        'deviation',
        'is_null_anomaly',
        'is_deviation_anomaly'
    ]
]

# Diisplay results
print(anomaly_df)

# Save Report
anomaly_df.to_csv(
    "ml_anomaly_report.csv",
    index=False
)

print("\nAnomaly report saved.")

# Save results to a seperate datafrmae
# XGBOOST
xgb_results_df = results_df.copy()

# Plot 5 random anomaly samples

import matplotlib.pyplot as plt
import pandas as pd

# Filter anomalies
march5_anomalies = anomaly_df[
    anomaly_df['datetime'].dt.date ==
    pd.to_datetime('2026-03-05').date()
]

# Randomly select 5 anomalies
sample_anomalies = march5_anomalies.sample(
    n=min(5, len(march5_anomalies)),
    random_state=42
)

# Plot
for idx, row in sample_anomalies.iterrows():

    site = row['site_name']

    anomaly_time = row['datetime']

    # Get 5th March data for site
    site_data = df[
        (
            df['site_name'] == site
        )
        &
        (
            df['datetime'].dt.date ==
            pd.to_datetime('2026-03-05').date()
        )
    ].copy()

    site_data = site_data.sort_values('datetime')

    # Create ML predictions
    model = models[site]

    X_val = site_data[features]

    site_data['PredictedTraffic'] = (
        model.predict(X_val)
    )

    # Actual Traffic Calculation
    site_data['ActualTraffic'] = (
        site_data['sum_dl_traffic_volume_gb']
    )

    # Create Plot
    plt.figure(figsize=(14,6))

    plt.plot(
        site_data['datetime'],
        site_data['ActualTraffic'],
        label='Actual Traffic'
    )

    # Predicted traffic
    plt.plot(
        site_data['datetime'],
        site_data['PredictedTraffic'],
        label='Predicted Traffic'
    )

    # Highlight Anomaly
    plt.scatter(
        row['datetime'],
        row['ActualTraffic'],
        s=180,
        label='Detected Anomaly'
    )

    # ANnomaly time marker
    plt.axvline(
        x=anomaly_time,
        linestyle='--'
    )

    # Plot the graphs
    plt.title(
        f"Actual vs Predicted Traffic with Anomaly - {site}"
    )

    plt.xlabel("Datetime")

    plt.ylabel("Traffic Volume (GB)")

    plt.xticks(rotation=45)

    plt.legend()

    plt.tight_layout()

    plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from prophet import Prophet

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Create Date Time
df['date'] = pd.to_datetime(df['date'])

df['datetime'] = (
    df['date'] +
    pd.to_timedelta(df['hour'], unit='h')
)

# Sort Data
df = df.sort_values([
    'site_name',
    'datetime'
])

# Prepare Prophet Format
prophet_df = df.copy()

prophet_df = prophet_df.rename(columns={
    'datetime': 'ds',
    'sum_dl_traffic_volume_gb': 'y'
})

# Remove timezone information from 'ds' column
if prophet_df['ds'].dt.tz is not None:
    prophet_df['ds'] = prophet_df['ds'].dt.tz_localize(None)

# Train and Validation Split

# Training Data
# 2nd March -> 4th March
train_df = prophet_df[
    (prophet_df['date'] >= '2026-03-02') &
    (prophet_df['date'] <= '2026-03-04')
].copy()

# Validation Data
# 5th March
val_df = prophet_df[
    (prophet_df['date'] == '2026-03-05')
].copy()

# Remove Nulls from Training
train_df = train_df.dropna(subset=['y'])

# TRrain Model per Site
models = {}
results = []
forecasts = {}

site_list = train_df['site_name'].unique()

for site in site_list:

    # Train Data
    site_train = train_df[
        train_df['site_name'] == site
    ][['ds', 'y']]

    # Validation Data
    site_val = val_df[
        val_df['site_name'] == site
    ][['ds', 'y']]

    # Skip weak sites
    if len(site_train) < 24 or len(site_val) == 0:
        continue

    try:

        # Prophet Model
        model = Prophet(
            daily_seasonality=True,
            weekly_seasonality=False
        )

        model.fit(site_train)

        models[site] = model

        # Predict Validation
        future = site_val[['ds']]

        forecast = model.predict(future)

        forecasts[site] = forecast

        # Merge Actual + Prediction
        merged = pd.merge(
            site_val,
            forecast[['ds', 'yhat']],
            on='ds'
        )

        merged = merged.dropna()

        if len(merged) == 0:
            continue

        # Metrics
        mae = mean_absolute_error(
            merged['y'],
            merged['yhat']
        )

        rmse = np.sqrt(
            mean_squared_error(
                merged['y'],
                merged['yhat']
            )
        )

        r2 = r2_score(
            merged['y'],
            merged['yhat']
        )

        results.append({
            'site_name': site,
            'MAE': mae,
            'RMSE': rmse,
            'R2': r2
        })

    except Exception as e:

        print(f"Skipping {site}: {e}")

# Results Table
results_df = pd.DataFrame(results)

print("\n===== PROPHET PERFORMANCE =====")
print(results_df)

# Overall Performance
print("\n===== OVERALL PERFORMANCE =====")

print("Average MAE :", results_df['MAE'].mean())
print("Average RMSE:", results_df['RMSE'].mean())
print("Average R2  :", results_df['R2'].mean())

# Anomaly Detection

ANOMALY_THRESHOLD = 1

anomaly_list = []

for site in forecasts.keys():

    forecast = forecasts[site][['ds', 'yhat']]

    actual = val_df[
        val_df['site_name'] == site
    ][['ds', 'y']]

    # Merge
    merged = pd.merge(
        actual,
        forecast,
        on='ds',
        how='left'
    )

    # Rename
    merged['ActualTraffic'] = merged['y']

    merged['PredictedTraffic'] = merged['yhat']

    # NULL Anomalies
    merged['is_null_anomaly'] = (
        merged['ActualTraffic'].isnull()
    )

    # Remove Zero Predictions
    merged = merged[
        merged['PredictedTraffic'] != 0
    ]

    # Deviation
    merged['deviation'] = (
        abs(
            merged['ActualTraffic']
            -
            merged['PredictedTraffic']
        )
        /
        merged['PredictedTraffic']
    )

    # Deviation Anomaly
    merged['is_deviation_anomaly'] = (
        merged['deviation'] > ANOMALY_THRESHOLD
    )

    # Final Anomalies
    anomalies = merged[
        (
            merged['is_null_anomaly']
        )
        |
        (
            merged['is_deviation_anomaly']
        )
    ].copy()

    anomalies['site_name'] = site

    anomaly_list.append(anomalies)

# Combine Anomalies
anomaly_df = pd.concat(anomaly_list)

# Select Output
anomaly_df = anomaly_df[
    [
        'ds',
        'site_name',
        'ActualTraffic',
        'PredictedTraffic',
        'deviation',
        'is_null_anomaly',
        'is_deviation_anomaly'
    ]
]

anomaly_df = anomaly_df.rename(columns={
    'ds': 'datetime'
})

# Display Anomalies
print("\n===== ANOMALY REPORT =====")
print(anomaly_df)

# Save Report
anomaly_df.to_csv(
    "prophet_anomaly_report.csv",
    index=False
)

print("\nAnomaly report saved.")

# Saveresults to a new data frame
# PROPHET
prophet_results_df = results_df.copy()

# Visualize Sample Site

sample_site = anomaly_df.iloc[10]['site_name']

forecast = forecasts[sample_site]

actual = val_df[
    val_df['site_name'] == sample_site
]

merged = pd.merge(
    actual,
    forecast[['ds', 'yhat']],
    on='ds'
)

# Plot
plt.figure(figsize=(14,6))

plt.plot(
    merged['ds'],
    merged['y'],
    label='Actual'
)

plt.plot(
    merged['ds'],
    merged['yhat'],
    label='Predicted'
)

# Highlight anomalies
site_anomalies = anomaly_df[
    anomaly_df['site_name'] == sample_site
]

plt.scatter(
    site_anomalies['datetime'],
    site_anomalies['ActualTraffic'],
    label='Anomaly'
)

plt.title(
    f"Prophet Forecast + Anomaly Detection - {sample_site}"
)

plt.xlabel("Datetime")

plt.ylabel("Traffic Volume (GB)")

plt.xticks(rotation=45)

plt.legend()

plt.tight_layout()

plt.show()

!pip install neuralprophet

# Neuralprophet Forecasting
# Training  : 2nd March -> 4th March
# Validation: 5th March

!pip uninstall -y torch torchvision torchaudio pytorch-lightning neuralprophet
!pip install neuralprophet torchvision torchaudio

# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import gc

from neuralprophet import NeuralProphet

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Create Date time
df['date'] = pd.to_datetime(df['date'])

df['datetime'] = (
    df['date'] +
    pd.to_timedelta(df['hour'], unit='h')
)

# Sort Data
df = df.sort_values([
    'site_name',
    'datetime'
])

# Prepare Data
neural_df = df.copy()

neural_df = neural_df.rename(columns={
    'datetime': 'ds',
    'sum_dl_traffic_volume_gb': 'y'
})

# Train/ Validation Split

# Train:
# 2nd March -> 4th March
train_df = neural_df[
    (neural_df['date'] >= '2026-03-02') &
    (neural_df['date'] <= '2026-03-04')
].copy()

# Validation:
# 5th March
val_df = neural_df[
    (neural_df['date'] == '2026-03-05')
].copy()

# Remove Nulls from Training
train_df = train_df.dropna(subset=['y'])

train_df['y'] = train_df['y'].astype('float32')
val_df['y'] = val_df['y'].astype('float32')

# Paramater Thresholds
ANOMALY_THRESHOLD = 1

# Store Results
results = []
anomaly_list = []
forecasts = {}

# Limit Number of Sites
site_list = train_df['site_name'].unique()[:50]

# Train Model per Site
for site in site_list:

    print(f"Processing Site: {site}")

    # Site Train Data
    site_train = train_df[
        train_df['site_name'] == site
    ][['ds', 'y']].copy()

    # Site Validation Data
    site_val = val_df[
        val_df['site_name'] == site
    ][['ds', 'y']].copy()

    # Skip weak sites
    if len(site_train) < 24:
        continue

    if len(site_val) == 0:
        continue

    try:

        # Lightweight Neuralprophet
        model = NeuralProphet(

            # Smaller lag window
            n_lags=12,

            # Forecast 1 step
            n_forecasts=1,

            # Seasonality
            daily_seasonality=True,
            weekly_seasonality=False,

            # Reduce complexity
            epochs=5,

            # Smaller learning rate
            learning_rate=0.01,

            # Disable unnecessary features
            yearly_seasonality=False
        )

        # Train Model
        model.fit(
            site_train,
            freq='H',
            progress='off'
        )

        # Create Future Data Frame
        future = model.make_future_dataframe(
            site_train,
            periods=len(site_val),
            n_historic_predictions=False
        )

        # Forecast
        forecast = model.predict(future)

        forecast = forecast.tail(len(site_val))

        # STtore only required columns
        forecast_small = forecast[
            ['ds', 'yhat1']
        ].copy()

        forecasts[site] = forecast_small

        # Merge Actual + Predicted
        merged = pd.merge(
            site_val,
            forecast_small,
            on='ds'
        )

        merged = merged.dropna()

        if len(merged) == 0:
            continue

        # Metrics
        mae = mean_absolute_error(
            merged['y'],
            merged['yhat1']
        )

        rmse = np.sqrt(
            mean_squared_error(
                merged['y'],
                merged['yhat1']
            )
        )

        r2 = r2_score(
            merged['y'],
            merged['yhat1']
        )

        results.append({
            'site_name': site,
            'MAE': mae,
            'RMSE': rmse,
            'R2': r2
        })

        # Anomaly Detection
        merged['ActualTraffic'] = merged['y']

        merged['PredictedTraffic'] = merged['yhat1']

        merged['deviation'] = (
            abs(
                merged['ActualTraffic']
                -
                merged['PredictedTraffic']
            )
            /
            merged['PredictedTraffic']
        )

        merged['is_null_anomaly'] = (
            merged['ActualTraffic'].isnull()
        )

        merged['is_deviation_anomaly'] = (
            merged['deviation']
            >
            ANOMALY_THRESHOLD
        )

        anomalies = merged[
            (
                merged['is_null_anomaly']
            )
            |
            (
                merged['is_deviation_anomaly']
            )
        ].copy()

        anomalies['site_name'] = site

        anomaly_list.append(anomalies)

        # Memory Cleanup
        del model
        del forecast
        del future
        del merged

        gc.collect()

    except Exception as e:

        print(f"Skipping {site}: {e}")

# Results Table
results_df = pd.DataFrame(results)

print("\n===== NEURALPROPHET PERFORMANCE =====")
print(results_df)

# Overall Performance
print("\n===== OVERALL PERFORMANCE =====")

print("Average MAE :", results_df['MAE'].mean())
print("Average RMSE:", results_df['RMSE'].mean())
print("Average R2  :", results_df['R2'].mean())

# Combine Anomalies
if len(anomaly_list) > 0:

    anomaly_df = pd.concat(anomaly_list)

    anomaly_df = anomaly_df[
        [
            'ds',
            'site_name',
            'ActualTraffic',
            'PredictedTraffic',
            'deviation',
            'is_null_anomaly',
            'is_deviation_anomaly'
        ]
    ]

    anomaly_df = anomaly_df.rename(columns={
        'ds': 'datetime'
    })

    print("\n===== ANOMALY REPORT =====")
    print(anomaly_df)

    anomaly_df.to_csv(
        "neuralprophet_anomaly_report.csv",
        index=False
    )

    print("\nAnomaly report saved.")

# Visualize Sample Site
if len(results_df) > 0:

    sample_site = results_df.iloc[0]['site_name']

    forecast = forecasts[sample_site]

    actual = val_df[
        val_df['site_name'] == sample_site
    ]

    merged_plot = pd.merge(
        actual,
        forecast,
        on='ds'
    )

    plt.figure(figsize=(14,6))

    plt.plot(
        merged_plot['ds'],
        merged_plot['y'],
        label='Actual'
    )

    plt.plot(
        merged_plot['ds'],
        merged_plot['yhat1'],
        label='Predicted'
    )

    plt.title(
        f"NeuralProphet Forecast - {sample_site}"
    )

    plt.xlabel("Datetime")

    plt.ylabel("Traffic Volume (GB)")

    plt.xticks(rotation=45)

    plt.legend()

    plt.tight_layout()

    plt.show()

# LSTM based Traffic Forecasting
# TRraining  : 2nd March -> 4th March
# Validation: 5th March

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn.preprocessing import MinMaxScaler

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras import backend as K

# Create Date time
df['date'] = pd.to_datetime(df['date'])

df['datetime'] = (
    df['date'] +
    pd.to_timedelta(df['hour'], unit='h')
)

# Sort Data
df = df.sort_values([
    'site_name',
    'datetime'
])

# Train and Validation  Split

# Train:
# 2nd March -> 4th March
train_df = df[
    (df['date'] >= '2026-03-02') &
    (df['date'] <= '2026-03-04')
].copy()

# Validation:
# 5th March
val_df = df[
    (df['date'] == '2026-03-05')
].copy()

# Remove Nulls from Training
train_df = train_df.dropna(
    subset=['sum_dl_traffic_volume_gb']
)

# Paramaters
LOOKBACK = 24
ANOMALY_THRESHOLD = 1

# Store Results
results = []
anomaly_list = []
forecasts = {}

# LIimit Number of Sites
site_list = train_df['site_name'].unique()[:50]

# Train Model per Site
for site in site_list:

    print(f"Processing Site: {site}")

    # Site Data
    site_train = train_df[
        train_df['site_name'] == site
    ].sort_values('datetime')

    site_val = val_df[
        val_df['site_name'] == site
    ].sort_values('datetime')

    # Skip weak sites
    if len(site_train) < LOOKBACK + 5:
        continue

    if len(site_val) == 0:
        continue

    try:

        # Target Series
        train_series = (
            site_train['sum_dl_traffic_volume_gb']
            .values
            .reshape(-1, 1)
        )

        # Scaling
        scaler = MinMaxScaler()

        train_scaled = scaler.fit_transform(
            train_series
        )

        # Create Sequences
        X_train = []
        y_train = []

        for i in range(LOOKBACK, len(train_scaled)):

            X_train.append(
                train_scaled[
                    i-LOOKBACK:i
                ]
            )

            y_train.append(
                train_scaled[i]
            )

        X_train = np.array(X_train)
        y_train = np.array(y_train)

        # Build light weight LSTM Model
        model = Sequential()

        model.add(
            LSTM(
                16,
                input_shape=(LOOKBACK, 1)
            )
        )

        model.add(Dense(1))

        model.compile(
            optimizer='adam',
            loss='mse'
        )

        # Train Model
        model.fit(
            X_train,
            y_train,
            epochs=5,
            batch_size=16,
            verbose=0
        )

        # Forecasting
        history = train_scaled[-LOOKBACK:]

        predictions = []

        for i in range(len(site_val)):

            X_input = history.reshape(
                1,
                LOOKBACK,
                1
            )

            y_pred_scaled = model.predict(
                X_input,
                verbose=0
            )

            y_pred = scaler.inverse_transform(
                y_pred_scaled
            )[0][0]

            predictions.append(y_pred)

            history = np.append(
                history[1:],
                y_pred_scaled
            )

        # Store Forecasts
        forecast_df = site_val[
            ['datetime']
        ].copy()

        forecast_df['PredictedTraffic'] = (
            predictions
        )

        forecast_df['ActualTraffic'] = (
            site_val[
                'sum_dl_traffic_volume_gb'
            ].values
        )

        forecasts[site] = forecast_df

        # Metrics
        merged = forecast_df.dropna()

        if len(merged) == 0:
            continue

        mae = mean_absolute_error(
            merged['ActualTraffic'],
            merged['PredictedTraffic']
        )

        rmse = np.sqrt(
            mean_squared_error(
                merged['ActualTraffic'],
                merged['PredictedTraffic']
            )
        )

        r2 = r2_score(
            merged['ActualTraffic'],
            merged['PredictedTraffic']
        )

        results.append({
            'site_name': site,
            'MAE': mae,
            'RMSE': rmse,
            'R2': r2
        })

        # Anomaly Detection
        merged['is_null_anomaly'] = (
            merged['ActualTraffic'].isnull()
        )

        merged = merged[
            merged['PredictedTraffic'] != 0
        ]

        merged['deviation'] = (
            abs(
                merged['ActualTraffic']
                -
                merged['PredictedTraffic']
            )
            /
            merged['PredictedTraffic']
        )

        merged['is_deviation_anomaly'] = (
            merged['deviation']
            >
            ANOMALY_THRESHOLD
        )

        anomalies = merged[
            (
                merged['is_null_anomaly']
            )
            |
            (
                merged['is_deviation_anomaly']
            )
        ].copy()

        anomalies['site_name'] = site

        anomaly_list.append(anomalies)

        # Clear Memory
        tf.compat.v1.reset_default_graph()

    except Exception as e:

        print(f"Skipping {site}: {e}")

# Results Table
results_df = pd.DataFrame(results)

print("\n===== LSTM PERFORMANCE =====")
print(results_df)

# Overall Performance
print("\n===== OVERALL PERFORMANCE =====")

print("Average MAE :", results_df['MAE'].mean())
print("Average RMSE:", results_df['RMSE'].mean())
print("Average R2  :", results_df['R2'].mean())

# Combine Anomalies
if len(anomaly_list) > 0:

    anomaly_df = pd.concat(anomaly_list)

    print("\n===== ANOMALY REPORT =====")
    print(anomaly_df)

    anomaly_df.to_csv(
        "lstm_anomaly_report.csv",
        index=False
    )

    print("\nAnomaly report saved.")

# Visualize Sample Site
if len(results_df) > 0:

    sample_site = results_df.iloc[0]['site_name']

    plot_df = forecasts[sample_site]

    plt.figure(figsize=(14,6))

    plt.plot(
        plot_df['datetime'],
        plot_df['ActualTraffic'],
        label='Actual'
    )

    plt.plot(
        plot_df['datetime'],
        plot_df['PredictedTraffic'],
        label='Predicted'
    )

    plt.title(
        f"LSTM Forecast - {sample_site}"
    )

    plt.xlabel("Datetime")

    plt.ylabel("Traffic Volume (GB)")

    plt.xticks(rotation=45)

    plt.legend()

    plt.tight_layout()

    plt.show()

# Save Results to a different dataframe
# LSTM
lstm_results_df = results_df.copy()

# =========================================================
# Compare Model Accuracy
# Models:
# 1. XGBoost
# 2. Prophet
# 3. LSTM

import pandas as pd
import matplotlib.pyplot as plt

# Create Comparison Table
comparison_df = pd.DataFrame({

    'Model': [
        'XGBoost',
        'Prophet',
        'LSTM'
    ],

    'MAE': [
        xgb_results_df['MAE'].mean(),
        prophet_results_df['MAE'].mean(),
        lstm_results_df['MAE'].mean()
    ],

    'RMSE': [
        xgb_results_df['RMSE'].mean(),
        prophet_results_df['RMSE'].mean(),
        lstm_results_df['RMSE'].mean()
    ],

    'R2': [
        xgb_results_df['R2'].mean(),
        prophet_results_df['R2'].mean(),
        lstm_results_df['R2'].mean()
    ]
})

# Display Results
print("\n===== MODEL COMPARISON =====")

print(comparison_df)

# Sort by R2 Score
comparison_df = comparison_df.sort_values(
    by='R2',
    ascending=False
)

# Plot MAE
plt.figure(figsize=(10,5))

plt.bar(
    comparison_df['Model'],
    comparison_df['MAE']
)

plt.title("Model Comparison - MAE")

plt.xlabel("Model")

plt.ylabel("MAE")

plt.tight_layout()

plt.show()

# Plot RMSE
plt.figure(figsize=(10,5))

plt.bar(
    comparison_df['Model'],
    comparison_df['RMSE']
)

plt.title("Model Comparison - RMSE")

plt.xlabel("Model")

plt.ylabel("RMSE")

plt.tight_layout()

plt.show()

# Plot R2 Score
plt.figure(figsize=(10,5))

plt.bar(
    comparison_df['Model'],
    comparison_df['R2']
)

plt.title("Model Comparison - R² Score")

plt.xlabel("Model")

plt.ylabel("R²")

plt.tight_layout()

plt.show()

# BEest Model
best_model = comparison_df.iloc[0]

print("\n===== BEST MODEL =====")

print(
    f"Best Performing Model : {best_model['Model']}"
)

print(
    f"Average R² Score      : {best_model['R2']:.4f}"
)

print(
    f"Average MAE           : {best_model['MAE']:.4f}"
)

print(
    f"Average RMSE          : {best_model['RMSE']:.4f}"
)