# -*- coding: utf-8 -*-
"""Another copy of Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhpGZ1UdTkSOFH8KCwCbxUEqaEfmfPmG
"""

import pandas as pd
import matplotlib.pyplot as plt

# =========================
# LOAD & PREPROCESS DATA
# =========================
df = pd.read_csv("/content/drive/MyDrive/Capstone/huawei_mbb_daily1.csv")

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Sort data
df = df.sort_values(by=['CellName', 'Date'])
df.head()

# Plot only top 5 cells by total traffic
top_cells = df.groupby('CellName')['DLTrafficGB'].sum().nlargest(5).index

plt.figure(figsize=(12, 6))

for cell in top_cells:
    cell_data = df[df['CellName'] == cell]
    plt.plot(cell_data['Date'], cell_data['DLTrafficGB'], label=cell)

plt.legend()
plt.show()

sample_cell = df['CellName'].iloc[0]

cell_data = df[df['CellName'] == sample_cell]

plt.figure(figsize=(10, 5))
plt.plot(cell_data['Date'], cell_data['DLTrafficGB'], marker='o')

plt.title(f"Traffic Pattern for Cell: {sample_cell}")
plt.xlabel("Date")
plt.ylabel("DL Traffic (GB)")
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

pip install pandas matplotlib prophet

# Rename for Prophet
df = df.rename(columns={
    'Date': 'ds',
    'DLTrafficGB': 'y'
})

train_end_date = "2026-03-20"

train_df = df[df['ds'] <= train_end_date]
test_df  = df[df['ds'] > train_end_date]

# 🚨 Remove null target values ONLY in training
train_df = train_df.dropna(subset=['y'])

# Optional: forward fill other columns in training only
train_df = train_df.fillna(method='ffill')

from prophet import Prophet

models = {}
forecasts = {}

for cell in train_df['CellName'].unique():

    cell_train = train_df[train_df['CellName'] == cell][['ds', 'y']]

    if len(cell_train) < 10:
        continue

    model = Prophet(
        daily_seasonality=True,
        weekly_seasonality=True
    )

    model.fit(cell_train)

    models[cell] = model

    # Forecast length = number of test days for this cell
    future_periods = len(test_df[test_df['CellName'] == cell])

    future = model.make_future_dataframe(periods=future_periods)

    forecast = model.predict(future)

    forecasts[cell] = forecast

from prophet import Prophet

models = {}
forecasts = {}

# Limit to first 100 unique cell names
cell_list = train_df['CellName'].unique()[:1000]

for cell in cell_list:

    cell_train = train_df[train_df['CellName'] == cell][['ds', 'y']]

    if len(cell_train) < 10:
        continue

    model = Prophet(
        daily_seasonality=True,
        weekly_seasonality=True
    )

    model.fit(cell_train)

    models[cell] = model

    # Forecast length = number of test days for this cell
    future_periods = len(test_df[test_df['CellName'] == cell])

    future = model.make_future_dataframe(periods=future_periods)

    forecast = model.predict(future)

    forecasts[cell] = forecast

#ignore nulls
from sklearn.metrics import mean_absolute_error

sample_cell = list(models.keys())[0]

forecast = forecasts[sample_cell]
actual = test_df[test_df['CellName'] == sample_cell][['ds', 'y']]

# Merge
merged = pd.merge(actual, forecast[['ds', 'yhat']], on='ds')

# 🚨 Drop nulls ONLY for evaluation (not training)
merged = merged.dropna()

mae = mean_absolute_error(merged['y'], merged['yhat'])

print("MAE:", mae)

import pandas as pd

anomaly_list = []

for cell in forecasts.keys():

    forecast = forecasts[cell][['ds', 'yhat']]

    # Actual test data (DO NOT drop nulls here)
    actual = test_df[test_df['CellName'] == cell][['ds', 'y']]

    # Merge predicted + actual
    merged = pd.merge(actual, forecast, on='ds', how='left')

    # 🚨 Identify NULL anomalies
    merged['is_null_anomaly'] = merged['y'].isnull()

    # 🚨 Avoid divide-by-zero
    merged = merged[merged['yhat'] != 0]

    # 🚨 Calculate deviation (only where actual is not null)
    merged['deviation'] = abs(merged['y'] - merged['yhat']) / merged['yhat']

    # 🚨 Identify deviation anomalies (>50%)
    merged['is_deviation_anomaly'] = merged['deviation'] > 0.5

    # 🚨 Combine both conditions
    anomalies = merged[
        (merged['is_null_anomaly']) | (merged['is_deviation_anomaly'])
    ].copy()

    # Add cell info
    anomalies['CellName'] = cell

    anomaly_list.append(anomalies)

anomaly_df = pd.concat(anomaly_list)

anomaly_df = anomaly_df[['CellName', 'ds', 'y', 'yhat', 'deviation',
                         'is_null_anomaly', 'is_deviation_anomaly']]

anomaly_df = anomaly_df.rename(columns={
    'ds': 'Date',
    'y': 'ActualTraffic',
    'yhat': 'PredictedTraffic'
})

print(anomaly_df)

anomaly_df.to_csv("anomaly_report.csv", index=False)

import matplotlib.pyplot as plt

sample_cell = anomaly_df['CellName'].iloc[30]

forecast = forecasts[sample_cell]
actual = df[df['CellName'] == sample_cell]

plt.figure(figsize=(12,6))

plt.plot(actual['ds'], actual['y'], label="Actual")
plt.plot(forecast['ds'], forecast['yhat'], label="Predicted")

# Highlight anomalies
cell_anomalies = anomaly_df[anomaly_df['CellName'] == sample_cell]

plt.scatter(cell_anomalies['Date'], cell_anomalies['ActualTraffic'], marker='o', label="Anomaly")

plt.legend()
plt.title(f"Anomaly Detection - {sample_cell}")

plt.show()